---

language: python
python:
  - "2.7.0"
  - "3.5.0"
services:
  - docker
install:
  - pip install wheel setuptools==18.5 molecule==2.19 ansible==2.7.11 docker
script:
  - molecule --version
  - ansible --version
  - molecule test