---

language: python
python:
  - "2.7"
  - "3.5"
services:
  - docker
install:
  - pip install molecule==2.19 ansible==2.7.11 docker
script:
  - molecule --version
  - ansible --version
  - molecule test