---
# tasks file for k3sagent
- name: Download the k3s binary for amd-linux
  get_url:
      url: "{{ k3s_release_url }}"
      dest: "{{ k3s_tmp_destination }}"
      mode: 0644
      checksum: sha256:https://github.com/rancher/k3s/releases/download/v0.8.0/sha256sum-amd64.txt

- name: Move the binary from tmp to usr/local/bin
  become: yes
  copy:
    src: "{{ k3s_tmp_destination }}"
    dest: "{{ k3s_final_destination }}"
    remote_src: yes
    mode: 0755

- name: Create k3s.service.env file for unit to start
  become: yes
  copy:
    content: ""
    dest: "{{ k3s_service_unit_env_file }}"
    owner: root
  

- name: Copy k3s.service to system
  become: yes
  template:
    src: templates/k3s.service.j2
    dest: /etc/systemd/system/k3s.service
    mode: 0644
  notify: reload_deamon_and_restart_service

- name: k3s agent service started
  become: yes
  systemd:
    name: k3s
    state: started
    enabled: yes
    daemon_reload: yes
