---
# defaults file for k3sagent
k3s_server_ip: 192.168.1.10
k3s_release_url: https://github.com/rancher/k3s/releases/download/v0.8.0/k3s
k3s_tmp_destination: /tmp/k3s
k3s_final_destination: /usr/local/bin/
k3s_service_unit_env_file: /etc/systemd/system/k3s.service.env